fix panic on drop
drop() must not pop() device from self.devices before calling
self.disconnect(fd), because disconnect expects to find the device in
self.devices, or it will panic:

thread 'main' panicked at 'There was no fd of 6', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/stick-0.7.1/src/ffi/linux.rs:119:9